services:
  - type: web
    name: jobnest
    env: node
    region: oregon
    plan: free
    buildCommand: |
      npm ci
      cd client && npm ci && npm run build
      cd ../server && npm ci
    startCommand: cd server && node index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: jobnest_db
          property: connectionString
      - key: PORT
        value: 6005
      - key: GROQ_API_KEY
        sync: false
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: SESSION_SECRET
        generateValue: true
      - key: DB_SSL
        value: "true"
    staticPublishPath: ./client/build

databases:
  - name: jobnest_db
    databaseName: jobnest
    plan: free
    ipAllowList: [] # only allow internal connections