services:
  - type: web
    name: jobnest
    env: node
    buildCommand: npm install && npm run install-all
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: jobnest_db
          property: connectionString
      - key: PORT
        value: 6005
      - key: GROQ_API_KEY
        sync: false
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: SESSION_SECRET
        generateValue: true

databases:
  - name: jobnest_db
    databaseName: jobnest
    plan: free